### ISSUE TITLE
Levo SL available data fields

### ISSUE THREAD

**Issue by putimir** [maca88/E-Bike-Edge-MultiField#2]
Hi, first of all: kudos for very promising and sophisticated app! 

I just tried it with my 2020 Levo SL bike, unfortunately I'm only getting these fields populated:

- Battery level (%)
- Remaining Range (always value of 1)
- Assist Mode
- Assist %

The others are empty. Do you have any ideas if I did not configure it properly or does the Levo SL have limited "telemetry stream" with only the above mentioned fields?

Thanks

**Comment by maca88** [comment]
Hi,

> Do you have any ideas if I did not configure it properly or does the Levo SL have limited "telemetry stream" with only the above mentioned fields?

unfortuantely it is the latter, Specialized implemented only a few fields from the ANT+ LEV Profile. Until Specialized decides to implement more fields in a future firmware there is nothing that we can do.
For example on my Giant only the following fields works:
- LEV Battery
- Assist Mode
- LEV Odometer
- Remaining Range (correct values)
- LEV Speed

so the working fields varies between ebike manufacturers that support ANT+.
