### ISSUE TITLE
No metric displayed

### ISSUE THREAD

**Issue by Hellnino18** [maca88/E-Bike-Edge-MultiField#5]
Hi @maca88 ,

Thanks for your great work. I was using the one from JanCapek before, but yours is more complete. I have only one problem with yours. There is no kmh / km displayed on my Garmin Edge 130. Only the values. Is there something to do ?

I tested in "metrics" dropdown menu in Garmin express, the 3 options but nothing change.

Thanks for your help.

Nath.

**Comment by maca88** [comment]
Hi,

> There is no kmh / km displayed on my Garmin Edge 130. Only the values. Is there something to do ?

That was intentionally done as the idea was to mimic the native behavior, which based on the pictures and videos, Edge 130 does not have units displayed for fields.

**Comment by Hellnino18** [comment]
OK, you right. I juste compared with your screen ;)

Thanks for your answer.
